In [1]:
import numpy as np
import pandas as pd

In [2]:
x = np.array([[1,0,3],[2,1,5],[3,1,2]])
y = np.array([1,6,2])
print(x.dot(y))

[ 7 18 13]


In [3]:
x = np.array([[1,3],[2,4],[0,5]])
y = np.array([[1,0],[2,3]])
print(x.dot(y))

[[ 7  9]
 [10 12]
 [10 15]]


In [4]:
x = np.array([[1,0,0],[0,1,0],[0,0,1]])
y = np.array([1,3,2])
print(x.dot(y))

[1 3 2]


In [5]:
x = np.array([[1,0,3],[2,1,5],[3,1,2]])
print(np.linalg.inv(x))

[[ 0.5        -0.5         0.5       ]
 [-1.83333333  1.16666667 -0.16666667]
 [ 0.16666667  0.16666667 -0.16666667]]


In [6]:
x = np.matrix([[1,0,3],[2,1,5],[3,1,2]])
x.getI()

matrix([[ 0.5       , -0.5       ,  0.5       ],
        [-1.83333333,  1.16666667, -0.16666667],
        [ 0.16666667,  0.16666667, -0.16666667]])

In [7]:
x = np.matrix([[1,0,3],[2,1,5],[3,1,2]])
x.getT()

matrix([[1, 2, 3],
        [0, 1, 1],
        [3, 5, 2]])

In [8]:
u = np.matrix([[1],[3],[-1]])
v = np.matrix([[2],[2],[4]])
print(u.getT().dot(v))

[[4]]


In [25]:
df = pd.DataFrame(columns=['midterm','midtermsquared','final'])
df.loc[1] = [89, 7921, 96]
df.loc[2] = [72, 5184, 74]
df.loc[3] = [94, 8836, 87]
df.loc[4] = [69, 4761, 78]
(df.loc[4]['midtermsquared'] - df['midtermsquared'].mean()) / (df['midtermsquared'].max()-df['midtermsquared'].min())

-0.4698159509202454

In [54]:
pattern = np.ones((24,4), float)
pattern

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
for i in range(2):
    pattern[1::4] = -1

In [57]:
pattern

array([[ 1.,  1.,  1.,  1.],
       [-1., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [-1., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [-1., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [-1., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [-1., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [-1., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])